version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - unconvert

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - url-shortener

    gofmt:
      simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
