// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Link struct {
	ID          int32        `json:"id"`
	OriginalUrl string       `json:"original_url"`
	ShortName   string       `json:"short_name"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type LinkVisit struct {
	ID        int32          `json:"id"`
	LinkID    int32          `json:"link_id"`
	Ip        string         `json:"ip"`
	UserAgent sql.NullString `json:"user_agent"`
	Referer   sql.NullString `json:"referer"`
	Status    int16          `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
