// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Link struct {
	ID          int32        `json:"id"`
	OriginalUrl string       `json:"original_url"`
	ShortName   string       `json:"short_name"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
