name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Тесты
  test:
    name: Test & Race Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      
      - run: go mod download
      
      - run: go test -race -v -coverprofile=coverage.out ./...
      
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          fail_ci_if_error: false

  # Линтер
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  # Сборка
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      
      - run: go build -v -o shortener ./cmd/url-shortener
      - run: test -f shortener && echo " Binary built successfully"
